coverage:
  status:
    project:
      default:
       target: 50%
       threshold: null
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success