coverage:
  status:
    project:
      default:
       target: 30%
       threshold: null
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
  ignore:
    - "src/main/java/com/webank/weid/util/HttpClient.java"
    - "src/test/**/*"