/*
 *       Copyright© (2018) WeBank Co., Ltd.
 *
 *       This file is part of weidentity-java-sdk.
 *
 *       weidentity-java-sdk is free software: you can redistribute it and/or modify
 *       it under the terms of the GNU Lesser General Public License as published by
 *       the Free Software Foundation, either version 3 of the License, or
 *       (at your option) any later version.
 *
 *       weidentity-java-sdk is distributed in the hope that it will be useful,
 *       but WITHOUT ANY WARRANTY; without even the implied warranty of
 *       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *       GNU Lesser General Public License for more details.
 *
 *       You should have received a copy of the GNU Lesser General Public License
 *       along with weidentity-java-sdk.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.webank.weid.protocol.base;

import java.util.Map;

import lombok.Data;

/**
 * Credential response.
 *
 * @author junqizhang 2019.04
 */
@Data
public class CredentialPojoWrapper {

    /**
     * Required: The Credential.
     */
    private CredentialPojo credential;

    /**
     * Required: The salts corresponding to the credential. The structure is same as specific cpt
     * type structure. There are three class files for one CPT, for CPT101, a example of this is
     * there are three class files generated by weidentity-build-tool, first one is Cpt101.java,
     * second one is Cpt101salt.java. And third one is Cpt101FieldsToBeDisclosed.java
     */
    private Map<String, Object> salt;
}
